---
- name: Install the required dhcpcd package
  ansible.builtin.package: name=isc-dhcp-server state=present

- name: Add our dhcpcd config
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload dhcpd

- name: Add our dhcpd defaults files
  ansible.builtin.template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload dhcpd

- name: Ensure the dhcpd service is enabled
  ansible.builtin.service:
    name: isc-dhcp-server
    state: started
    enabled: True
